### ISSUE TITLE
[openstack] [build image] Stop the VM before saving the image

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamConnectors#101]
Even if not required on OpenStack, it's better to stop the VM to prevent random disk consistency issues.

**Comment by schaubl** [comment]
still valid

**Comment by loomis** [comment]
And customers have now run into this issue.  See https://support.sixsq.com/helpdesk/tickets/3017.

**Comment by schaubl** [comment]
Doesn't apply anymore.
