### ISSUE TITLE
[stratuslab] connector fails to terminate VMs of a run when some VMs are already teminated

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#103]
This is the run on BB where it was discovered https://bb1.hnx.helix-nebula.eu/run/98b10b38-ac98-43ea-a186-1a824f70ddf3

There might have been a hiccup on the cloud side to terminate all the VMs of the run initially.  Now, the run termination request successfully returns, but VMs are not getting terminated.

**Comment by loomis** [comment]
Connector is being discontinued.  Enhancements/fixes will not be made.
