### ISSUE TITLE
use StratusLab Runner interface rather than OpenNebula Runner class

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#13]
Moved from https://github.com/slipstream/SlipStreamClient/issues/2

The StratusLab client has been refactored to allow backward compatibility with previous StratusLab deployments while supporting the newer CIMI interface for new deployments.

The SlipStream client relies directly on the Runner class for OpenNebula. This will fail when StratusLab infrastructures deploy a newer StratusLab release. The client should be refactored to use the interface and add a parameter to switch between which is active for a given infrastructure.

**Comment by schaubl** [comment]
@konstan Is it still relevant ?

**Comment by loomis** [comment]
Connector is being discontinued.  Enhancements/fixes will not be made.
