### ISSUE TITLE
openstack connector leaks floating ips

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamConnectors#138]
The OpenStack connector as configured on the CloudFerro infrastructure (eocloud.eu) leaks floating IP addresses.  All of the addresses allocated to machines remain allocated after the application has been terminated.

**Comment by konstan** [comment]
There seems to be an issue with leaking IPs on the primary subnet as well.  See https://github.com/SixSq/tasklist/issues/1120

**Comment by konstan** [comment]
I wasn't able to fix it.  Here is the email sent to CloudFerro http://support.sixsq.com/helpdesk/tickets/1652 and the corresponding ticket on their side https://eocloud.cloudferro.com/viewticket.php?tid=491909&c=bWgGmu6g
