### ISSUE TITLE
Test/check physical connector

### ISSUE THREAD

**Issue by mebster** [slipstream/SlipStreamConnectors#23]

**Comment by konstan** [comment]
Related: #24

**Comment by konstan** [comment]
- [ ] Run doesn't get aborted if case of Orch or machine instantiation errors. (E.g., `com.jcraft.jsch.JSchException: SSH_MSG_DISCONNECT: 2 Too many authentication failures for root ` but run doesn't reflect this.)
- [ ] Simple run uses Orch's IP (defined in User params), instead image ID from `"Cloud Image Identifiers and Image Hierarchy"` -> `"Cloud image IDs"` should be used (which should be the actual IP of the host.)
- [ ] With the current model it's not possible to run concurrent deployments which use the same images as the images refer to the same IPs. Solution: locking mechanism or require IP to be set as "mandatory" run parameter during the instantiation of the run.

**Comment by konstan** [comment]
After discussion with @mebster: Need a short discussion with the rest of the team on possible use-cases for the connector.  This will allow to better scope the further development/improvement of the connector and/or extension of the SlipStream usage models (provided this turns out to be useful).

**Comment by konstan** [comment]
As the result:
1. The connector was removed from all the Nexus and YUM repos and RPM artefact stopped to be produced (see #27) until the below issues are addressed.
2. The connector should be migrated to the latest `Java->Python CLI` pattern (see #28) and making sure it works as is now by testing and fixing issue (e.g., #29)
3. To be able to offer the connector for a public usage, #30 (concurrent runs on the same image(s)) should be addressed.
