### ISSUE TITLE
The StratusLab connector is using his custom machanisme to build image instead of ...

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamConnectors#26]
... using the SS one like all other connectors [`_build_image_increment`](https://github.com/slipstream/SlipStreamClient/blob/v2.8-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L367).

This prevent it to benefit from update in the SS `_build_image_increment`.
Example: 
The addition of `export DEBIAN_FRONTEND` in [`get_packages_install_command`](https://github.com/slipstream/SlipStreamClient/blob/v2.8-community/client/src/main/python/slipstream/util.py#L563) which allow to install some packages like MySQL on Debian based OS. 
Without this, the installation will hang because it will be waiting forever a user input.

**Comment by schaubl** [comment]
@mebster @loomis Do we still: 
- support StratusLab ?
- enhance the connector ?

If not, I think we can close this issue.

**Comment by loomis** [comment]
I think that we have to support StratusLab as long as we have StratusLab-based clouds on HNX.  Enhancements are possible, if critical, but otherwise should not be considered.

**Comment by schaubl** [comment]
Ok, so I will close this issue (at least for now)
