### ISSUE TITLE
OpenStack: Add support for Floating IPs

### ISSUE THREAD

**Issue by schaubl** [slipstream/SlipStreamConnectors#34]

**Comment by vincent-legoll** [comment]
There's a proposal of what & how it could be done here: [sixsq ticket #487](http://support.sixsq.com/support/tickets/487)

**Comment by schaubl** [comment]
The support ticket is private so I copied the content of the proposal here:
```
here is what I devised for making SS usable with floating IPs:

Scope:

Not the full blown thing, just basic functionality & sane default values...

UI elements:

Where: Home / Configuration / for each connector instance
What: a checkbox (just under public network mapping) : "public network uses/provides floating IPs" (default value: true for openstack, false instead)
This checkbox makes private network mandatory (as the underlying network, upon which f-IPs are virtually implemented). This needs to be explained in the contextual popup window.
This checkbox is greyed unless there's something entered in "public network mapping"

Actions:

VM UP
1 - connector instance checkbox is true? No! boot VM with public net as done today
2 - Yes! boot VM with private network
3 - f-IP available? No! Report "Floating IP pool XXX for network YYY depleted, please contact your cloud administrator." Adn then mark VM as "degraded" mode.
4 - Yes! get one of the available f-IPs
5 - associate it to the VM
6 - update "machine:url.ssh" link to be f-IP based

VM DOWN
1 - deassociate from VM

Implementation details:

OpenStack API: "compute API V2 extensions"
http://developer.openstack.org/api-ref-compute-v2-ext.html

GET - /v2/​{tenant_id}​/os-floating-ips - List floating IPs
POST - /v2/​{tenant_id}​/servers/​{server_id}​/action - Adds / Removes a floating IP address to an instance.

With this, it'll probably cover a big part of openstack deployments.
```

**Comment by vincent-legoll** [comment]
Could you approximately explain what modifications would be required to implement that, I mean which files to modify, etc... In a few words to get someone started on the right track.

**Comment by schaubl** [comment]
I would start by adding a parameter `Floating IP` in images. This can be done here: https://github.com/slipstream/SlipStreamConnectors/blob/master/openstack/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackImageParametersFactory.java
Since one of the goals of Floating IPs is to get a specific IP, this parameter should allow to take an IP address or `auto` if the user want to pick the first address available.
Then this parameter should be transferred to the CLI. This can be done here: https://github.com/slipstream/SlipStreamConnectors/blob/master/openstack/jar/src/main/java/com/sixsq/slipstream/connector/openstack/OpenStackConnector.java#L79
Then the CLI should accept this new parameter. This can be done here: https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/scripts/openstack-run-instances#L64
Then the connector has to be able to request the Floating IP. This can be done here: https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/cloudconnectors/openstack/OpenStackClientCloud.py#L169
Then, at the end of the deployment the IP should be released (if needed). This has to be done here: https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/cloudconnectors/openstack/OpenStackClientCloud.py#L180 and here https://github.com/slipstream/SlipStreamClient/blob/master/client/src/main/python/slipstream/cloudconnectors/openstack/OpenStackClientCloud.py#L185

**Comment by vincent-legoll** [comment]
Thanks, I'll have a look

**Comment by schaubl** [comment]
Duplicate of #10.

**Comment by vincent-legoll** [comment]
I have a problem running SS-trunk. I followed "Running locally", when adding my OpenStack connector. I put "my-openstack:com.sixsq.slipstream.connector.openstack.OpenStackConnector" in settings/SS Basics, click on "Save"...
```
The server encountered an unexpected condition which prevented it from fulfilling the request
Error 500 - Server Error
```
And on "mvn jetty:run-war" console, I got that output:

```[...]
Caused by: com.sixsq.slipstream.exceptions.SlipStreamRuntimeException: com.sixsq.slipstream.exceptions.SlipStreamRuntimeException cannot load cloud connector for com.sixsq.slipstream.connector.openstack.OpenStackConnector using key openstack
[...]```

That is without any modifications to code. Current git for all modules, mvn 3.3.3, oracle JDK 8 x64 on ubuntu 14.04

Am I missing something ?

**Comment by vincent-legoll** [comment]
Trying with "test-cloud:local" is working...

**Comment by schaubl** [comment]
`my-openstack:openstack` is enough, it's not needed to add the full Class name.

To start SlipStream through `mvn jetty:run-war` with some additional connectors, you have to uncomment them in the following pom file: https://github.com/slipstream/SlipStreamServer/blob/master/war/pom.xml#L54

**Comment by vincent-legoll** [comment]
Thanks, this is working. Maybe that info could be added to the "Running locally" page...

**Comment by vincent-legoll** [comment]
Is there a way to completely disable the "Fancy a tour?" popup for all users ?

**Comment by rbf** [comment]
> Is there a way to completely disable the "Fancy a tour?" popup for all users ?

No.

**Comment by mebster** [comment]
Why would you want to take this feature away for all users? Is there something wrong with it?

**Comment by vincent-legoll** [comment]
I'm not deploying a production SS, I'm in development mode (all users are just: me and myself), and it's getting slightly annoying...

**Comment by mebster** [comment]
Understood. Can you create an issue on the ui?

**Comment by vincent-legoll** [comment]
Done: https://github.com/slipstream/SlipStreamUI/issues/356

**Comment by rbf** [comment]
In the meantime, does it work for you to disable it when asked? (see button highlighted in the screenshot below)

![disable_tour](https://cloud.githubusercontent.com/assets/807084/8328676/06764b1e-1a73-11e5-98bc-8b6efdf3acb2.png)

> Maybe the way is in modifying the code locally...

You might outcomment the JS code that starts it:

https://github.com/slipstream/SlipStreamUI/blob/master/clj/resources/static_content/js/tours/alice-intro-welcome.js#L59-L67

**Comment by vincent-legoll** [comment]
disregard the "fancy a tour" comments, its working

**Comment by vincent-legoll** [comment]
Hello, any news on your front, about the floating-ip feature ? As this would be a huge enabler...
