### ISSUE TITLE
Calculation of the root disk size fails on stratuslabiter connector

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#57]
On StratusLabIter connector, root disk size calculation should try to avoid taking into account extra disks.  Especially, substituting the root disk size by the extra disk size (as this is seen below `86731, Running, 212.128.52.81, 1, 1536, 1,` - should have been 6 instead of 1).  In the case of stratuslabiter connector the volatile extra disks get created on PDisk, which complicates the matter. 

```
[root@bluebox stratuslabiter-pdisk-742]# /usr/bin/stratuslabiter-describe-instances  -t 60 --password xxx --endpoint '154.48.152.10' --username sixsquser -vvv
id, state, ip, cpu [nb], ram [MB], root disk [GB], instance-type [name]
85709, Running, 212.128.48.49, 1, 1536, 6,
86712, Running, 212.128.52.62, 1, 1024, 6,
86713, Running, 212.128.52.63, 1, 1024, 6,
86731, Running, 212.128.52.81, 1, 1536, 1,
[root@bluebox stratuslabiter-pdisk-742]#
```

**Comment by konstan** [comment]
The solution is to have the patch to StratusLab client merged
https://github.com/StratusLab/client/pull/160

This brings updates to rendering of the template of the running VM on cloud. It separates and numbers the VM disks for easier information retrieval on the client side (SS SL connector) of the driver (SL client).

**Comment by loomis** [comment]
Connector is being discontinued.  Enhancements/fixes will not be made.
