### ISSUE TITLE
[occi] getters on User object no longer raise exceptions if attribute is not found - update the code accordingly

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#70]
When testing, Enol (EGI) stumbled upon the following issue:

```
ss:abort- Exception with detail: sequence item 8: expected string, NoneType found
```

This turned out to be related to None returned by `user_info.user_info.get_cloud('proxy_file')` 
https://github.com/slipstream/SlipStreamConnectors/blob/master/occi/python/tar/slipstream_occi/OcciClientCloud.py#L146
i.e. when the attribute is not found `user_info.get_cloud('proxy_file')` doesn't raise, but rather returns None (by default).

**Comment by schaubl** [comment]
Yes, this is the default behaviour.
Changing this behaviour will probably break other connectors.
The connector should check itself and raise if needed.

**Comment by konstan** [comment]
Indeed.   The connector was written more than year ago, when I think the getters on UserInfo were still raising.  I've updated the implementation accordingly on the testing instance and asked Enol to test.

**Comment by konstan** [comment]
Updated.  On the test OCCI instance the change fixes the issue.
