### ISSUE TITLE
[occi] Latest version of OCCI requires full urls to query resources

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#74]
Required to be fixed to unblock EGI with their OCCI tests.

**Comment by konstan** [comment]
It looks that different EGI OCCI sites handle the queryable resource `--resource <name>` differently.  Some expect it to be qualified with the site's endpoint, some don't.

|`--resource compute` | `--resource <site-url>/compute`|
|:---------:|:---------:|
|CYFRONET | IFCA (occi1.1) |
The table is not complete.  To be updated.

**Comment by loomis** [comment]
OCCI no longer supported.  Closing...
