### ISSUE TITLE
update openstack connector for Keystone API v3

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStreamConnectors#75]
Update the OpenStack connector to support both the Keystone API v2 (current implementation) and also v3 (available in libcloud but not yet used by connector).

**Comment by rbf** [comment]
When doing this issue, please validate the `cyclone-fr2` connector on nuv.la.

**Comment by schaubl** [comment]
@rbf: Please see the comment [here](https://github.com/SixSq/tasklist/issues/579#issuecomment-182333895).

**Comment by schaubl** [comment]
This issue continue in #90
