### ISSUE TITLE
[occi] allow to use Ubuntu for Orchestrator VM

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#76]
Detect Ubuntu, provide EGI APT repo and install rOCCI CLI
https://github.com/slipstream/SlipStreamConnectors/blob/master/occi/python/tar/slipstream_occi/OcciClientCloud.py#L287

**Comment by konstan** [comment]
In `issue_#76-occi-ubuntu-orch` branch.

**Comment by loomis** [comment]
OCCI connector no longer supported. Closing...
