### ISSUE TITLE
[openstack] on timeout of waiting for IP for a VM we don't publish VM's ID to the run

### ISSUE THREAD

**Issue by konstan** [slipstream/SlipStreamConnectors#80]
This prevents from stopping the VM later on from SlipStream.

This happened at CYFRONET.  https://nuv.la/run/30a89a5f-7e3b-419b-9604-a77177442730

The tenant used at CYFRONET didn't have IPs  (to be confirmed) or there was an issue assigning one.  However, the image configures to request public IP.  When the code times out on waiting for IPs the abort is raised `ss:abort- Timed out while waiting for IPs to be assigned to instances: fc28eb3c-0001-40f5-bf05-9af6a67870bc`, but the VM ID is not published on the run.  

Solution: IMO, we can attempt the publication of the VM ID to the run, so that user can properly terminate it from SlipStream w/o needing to go away to the cloud directly.

**Comment by schaubl** [comment]
It should be already done. The method [`__add_vm`](https://github.com/slipstream/SlipStreamClient/blob/v2.21-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L440) is called [here](https://github.com/slipstream/SlipStreamClient/blob/v2.21-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L418), before the IP is retrieved [here](https://github.com/slipstream/SlipStreamClient/blob/v2.21-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L421) and [`__add_vm`](https://github.com/slipstream/SlipStreamClient/blob/v2.21-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L440) calls [`_publish_vm_id`](https://github.com/slipstream/SlipStreamClient/blob/v2.21-community/client/src/main/python/slipstream/cloudconnectors/BaseCloudConnector.py#L452) if the ID is available.

**Comment by schaubl** [comment]
Closing it for now
